# Basic settings
set -g default-terminal "tmux-256color"
set -g terminal-features "xterm-256color:RGB"
set -g mouse on
set -g set-clipboard on
set -sg escape-time 0
set -g history-limit 500000

unbind C-b
set -g prefix C-g
bind-key C-g send-prefix

bind -n M-z send-keys ""

set -g bell-action any
set -g visual-bell off
set -g visual-activity off

# Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Pane
unbind %
unbind '"'
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

bind -n M-C-h select-pane -L
bind -n M-C-j select-pane -D
bind -n M-C-k select-pane -U
bind -n M-C-l select-pane -R

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Windows
bind -n M-C-p previous-window
bind -n M-C-n next-window

bind c new-window -c "#{pane_current_path}"

# Copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Palette
set -g @bg     "#1d2225"
set -g @bg_dim "#161a1d"
set -g @bg1    "#262e31"
set -g @bg2    "#2d3539"
set -g @bg3    "#2e3538"
set -g @bg4    "#2f3437"
set -g @bg5    "#2f3735"

set -g @fg     "#c6ba9f"
set -g @red    "#e77e80"
set -g @green  "#a8c181"
set -g @orange "#e69975"
set -g @yellow "#dbbd80"
set -g @blue   "#80bcb4"
set -g @purple "#d699b7"
set -g @aqua   "#82c091"

# Status bar
set -g status-style "fg=#{@fg}"
set -g status-left-length 100
set -g status-right-length 100

set -g status-left \
"#[fg=#{@red},bold][#S] #[default]"

set -g window-status-format \
"#[fg=#{@fg}]#I:#W#F"

set -g window-status-current-format \
"#[fg=#{@green},bold]#I:#W#[fg=#{@orange}]#F"

set -g status-right \
"#[fg=#{@blue},bold][ %H:%M ]#[default]"

set -g pane-border-style "fg=#{@bg5}"
set -g pane-active-border-style "fg=#{@aqua}"
